name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Getting image tag
        id: tag
        run: |
          echo DDNET_SIMPLE_TAG="$(grep 'ARG DDNET_VERSION=' ddnet-simple/Dockerfile | cut -d'=' -f2)" >> $GITHUB_OUTPUT

      - name: Publish ddnet-simple
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ddnet-simple
          push: true
          tags: |
            docker.io/chillerdragon/ddnet-simple:${{ steps.tag.outputs.DDNET_SIMPLE_TAG }}
            docker.io/chillerdragon/ddnet-simple:latest
